version: '3.8'

services:
  main-db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ad_center
      MYSQL_USER: admin
      MYSQL_PASSWORD: WADIZ!@#123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
